### ISSUE TITLE
Opportunities that are booked outside of their validFromBeforeStartDate window seem to succeed if openBookingPrepayment=Unavailable

### ISSUE THREAD

**Issue by lukehesluke** [openactive/OpenActive.Server.NET#127]
[common-error-conditions_not-bookable_OpenBookingSimpleFlow_ScheduledSession.md](https://github.com/openactive/OpenActive.Server.NET/files/6386717/common-error-conditions_not-bookable_OpenBookingSimpleFlow_ScheduledSession.md)

An example of a run that succeeded and did not have openBookingPrepayment=Unavailable:

[common-error-conditions_not-bookable_OpenBookingSimpleFlow_FacilityUseSlot.md](https://github.com/openactive/OpenActive.Server.NET/files/6386725/common-error-conditions_not-bookable_OpenBookingSimpleFlow_FacilityUseSlot.md)

**Comment by lukehesluke** [comment]
Actually, this one passed and it has `openBookingPrepayment=Unavailable`:

[common-error-conditions_not-bookable_OpenBookingApprovalFlow_FacilityUseSlot.md](https://github.com/openactive/OpenActive.Server.NET/files/6386728/common-error-conditions_not-bookable_OpenBookingApprovalFlow_FacilityUseSlot.md)

Therefore I wonder if this issue only happens when `openBookingPrepayment=Unavailable` and price ≠ 0 🤔

**Comment by lukehesluke** [comment]
Not sure if this is a different issue or not, but this test ran at about 12:12 (BST), 29th April. It asked for a `TestOpportunityBookableOutsideValidFromBeforeStartDate` session and received one with:

```json
"startDate": "2021-05-03T10:24:47+00:00",
"superEvent.offers[0].validFromBeforeStartDate": "P3DT23H7M",
```

This means that the validFrom window started at 12:17 (BST). The test took 23 minutes to run and therefore the test failed because this condition no longer held by the time it had run.

Short term suggestion:

* Make Ref Impl use a tighter window (maybe no earlier than 90 minutes into the future?) when responding to `TestOpportunityBookableOutsideValidFromBeforeStartDate`
* Recommend that other Booking Systems do the same

Longer term suggestion:

* Make `TestOpportunityBookableOutsideValidFromBeforeStartDate`'s description (in test interface docs) and Shape Expressions all indicate that the validFrom window must start at least 90 mins in the future

**Comment by lukehesluke** [comment]
I can see now that this is also the cause of the issue in the 1st comment

**Comment by nickevansuk** [comment]
Yes this matches my findings also - the .NET code seems to have a very clear validFromBeforeStartDate logic check which looks correct, so had started looking in a similar direction

The issues above are all in Random mode though, so it looks like this might be an issue with the broker/constraints?

**Comment by nickevansuk** [comment]
As the test suite runs constraint checks against anything that gets from .NET or the broker, if we’re seeing invalid data coming from the booking system or broker's test interface and it’s getting past the constraint validation in the test suite, the constraints are likely faulty?

The above reports are all from random mode rather than controlled mode, which further supports that theory?

**Comment by nickevansuk** [comment]
Another related issue here:
 
[booking-window_opportunity-outside-range-c1-c2_OpenBookingSimpleFlow_ScheduledSession.md](https://github.com/openactive/OpenActive.Server.NET/files/6398779/booking-window_opportunity-outside-range-c1-c2_OpenBookingSimpleFlow_ScheduledSession.md)

**Comment by nickevansuk** [comment]
Fixed by https://github.com/openactive/openactive-test-suite/pull/394
